# Generated by Django 4.1.4 on 2023-03-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000)),
                ('Address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('Postion', models.CharField(choices=[('Clerk', 'Clerk'), ('Manager', 'Manager'), ('Devloper', 'Devloper'), ('Other', 'Other')], max_length=200)),
            ],
        ),
    ]
